- setup.cfg
Currently the `LICENSE` file isn't included in the source tarball on PyPI
> Inculde license in source tarball

- .lgtm.yml
LGTM uses Python 2 by default. Tell it to use Python 3.
Signed-off-by: Stefan Weil <sw@weilnetz.de>
> Add configuration for LGTM static code analyzer

- .gitlab-ci.yml
- calamari_ocr/ocr/augmentation/__init__.py
- calamari_ocr/ocr/backends/backend_interface.py
- calamari_ocr/ocr/backends/model_interface.py
- calamari_ocr/ocr/backends/tensorflow_backend/tensorflow_backend.py
- calamari_ocr/ocr/backends/tensorflow_backend/tensorflow_model.py
- calamari_ocr/ocr/codec.py
- calamari_ocr/ocr/datasets/__init__.py
- calamari_ocr/ocr/datasets/abbyy_dataset/dataset.py
- calamari_ocr/ocr/datasets/dataset.py
- calamari_ocr/ocr/datasets/file_dataset.py
- calamari_ocr/ocr/datasets/input_dataset.py
- calamari_ocr/ocr/datasets/pagexml_dataset/dataset.py
- calamari_ocr/ocr/evaluator.py
- calamari_ocr/ocr/predictor.py
- calamari_ocr/ocr/trainer.py
- calamari_ocr/scripts/train.py
- calamari_ocr/utils/multiprocessing.py
Support for loading training and validation data on the fly. Required params:
`--train_data_on_the_fly` and/or `--validation_data_on_the_fly`
To prevent the automatic codec computation (requires the loading of all text examples once) you can pass:
`--no_auto_compute_codec` and give a `--whitelist` with all the characters. Note that Calamari will crash atm if not all occurring characters are listed as soon as an unknown char is read.
On my setup this slows down the training by a factor of almost 10 due to loading from a HDD on a NFS. Possibly the difference will be lower when using a SSD.
The code is highly experimental, cause it is only roughly tested.
> Loading training and validation data on the fly

- calamari_ocr/ocr/backends/tensorflow_backend/tensorflow_model.py
- calamari_ocr/ocr/predictor.py
Fixed bug, that the longer the prediction the longer it takes. Reason is that the graph got increased in size for each batch (called `prepare`). Now `reset_data` is called, but also fixed: `prepare` does not recreate initialize operations on each call (increasing graph size!).
> Fixed prediction using reset data instead of prepare

- calamari_ocr/scripts/predict.py
- calamari_ocr/scripts/train.py
We're experimenting with automated training workflows and one interesting variable is whether the engine was updated. Also, for provenance's sake it's important to know the version of the engine a model was trained with.
> Add --version flag to train and predict script

- calamari_ocr/ocr/trainer.py
When working with preprocessed bidirectional data, the text preprocessor has to be applied to the model output but not to ground truth data. To achieve this, the trainer needs an additional argument.
> Evaluation preprocessor argument added to trainer

- calamari_ocr/ocr/datasets/pagexml_dataset/dataset.py
Added additional check for TextEquivs per TextLine.
Previous approach may have ignored TextLines if no TextEquiv with a given index existed.
Which would result in a mismatch between ground truth and recognition data in PAGEXML datasets.
> Added TextEquiv check per TextLine

- calamari_ocr/ocr/datasets/pagexml_dataset/dataset.py
Respect orientation parameter of TextRegions in Page XML
Orientation as it is described in the official (Page XML schema](https://www.primaresearch.org/schema/PAGE/gts/pagecontent/2019-07-15/pagecontent.xsd):
> The angle the rectangle encapsulating the page (or its Border) 
> has to be rotated in clockwise direction in order to correct the present skew
> (negative values indicate anti-clockwise rotation).
> Range: -179.999,180
Orientation will now be read from the TextRegion/parent of each TextLine and saved in sample.
A skew correction with the orientation angle will only take place if an orientation angle exists, is not 0 and not a multiple of 360. Angles beyond [-179.999,180] are supported, even if the official Page XML does not support them.
Note: 
* orientation is described as the …
> Read and apply textline orientation from pagexml

- calamari_ocr/ocr/datasets/pagexml_dataset/dataset.py
Works around a issue I had while working with some PageXML files that where edited and saved with Aletheia.
In my PageXML files `TextEquiv` does not have an index attribute, i.e. things look like this:
```
<TextLine><TextEquiv><Unicode>bla bla bla</Unicode></TextEquiv></TextLine>
```
Currently, Calamari will not find such `<TextEquiv>` tags. This PR adds a fallback for this case and just uses any `<TextEquiv>` tags without `index` attributes.
> PageXML: allow TextEquiv without index attribute

- calamari_ocr/ocr/datasets/pagexml_dataset/dataset.py
Changes the fallback behavior for selecting TextEquivs (which was initially introduced in f3514e9c8ac02b03fb3161965df6e029e476fe95) so that only TextEquivs __without an index__ attribute are selected when no TextEquiv with the selected `text_index` is found in a `TextLine` element.
This avoids training e.g. on _predicted text_ in cases where _ground truth_ in a TextEquiv is identified by `index="0"` and _predicted text_ by `index="1"`. With the current fallback behavior Calamari would treat the predicted text as training data when no GT-TextEquiv exists in the same Textline (when text_index is set to 0).
> Only select TextEquivs without index when fallback mechanism is triggered

- setup.py
main() in calamari-predict-and-eval can not be called without arguments...
> Fix cli for predict-and-eval in setup.py

- README.md
s/`calamari_ocr`/`calamari-ocr`/
Typo, I guess. `calamari_ocr` downloads calamari v1.0.5.
> changed typo in README

- calamari_ocr/ocr/dataset/datareader/pagexml/reader.py
The way opencv returns rotation angles is quite opaque. I need to set an maximum for the angle to prevent the lines from spinning out of control.
This is only relevant for use as a library. I could have introduced a command line parameter for that behaviour, but since PageXMLDatasetLoader sets "orientation" to "0" when the attribute is not present in the PAGE XML, this would have meant some interdependency between command line parameters that would have been hard to understand for the user.
> Fix for auto rotation of PageXML lines (not used in CLI)

- calamari_ocr/ocr/dataset/datareader/pagexml/reader.py
I accidentally reverted my own fix that prevented the PAGE reader from including existing OCR text in the GT...
> Prevent PageXML training on previous OCR results

- calamari_ocr/ocr/dataset/imageprocessors/final_preparation.py
- calamari_ocr/test/test_prediction.py
- calamari_ocr/utils/image.py
When normalize=False is set, FinalPreparation must not multiply the data with 255. Otherwise it renders many line images unreadable.
> Fix final_preparation for already normalized data

- setup.cfg
This fixes these warnings:
UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
Usage of dash-separated 'licence-file' will not be supported in future versions. Please use the underscore name 'licence_file' instead
Signed-off-by: Stefan Weil <sw@weilnetz.de>
> Update setup to fix build warnings

- calamari_ocr/ocr/dataset/datareader/pagexml/reader.py
> Return empty images for PageXML lines without coords

- calamari_ocr/ocr/dataset/datareader/pagexml/reader.py
This PR adds a new CLI parameter `--data.delete_old_words` to the `PageXMLReader`, which defaults to `True`. Prior to this PR, if an input PageXML file already had `Word` tags in it, Calamari would just kind of make a mess in the output...
With this option enabled, the words from the input will simply be removed from the element tree prior to writing the new ones. If disabled, the suffix `_old` will be appended to the IDs of all the existing words and their glyphs.
Previously, I tried to fix this issue by simply overwriting Word tags, which did not work out as smoothly. Remnants of this still exist in this PR, but due to the CLI parameter, this code works effectively the same as before. This can be reverted if needed.
> PageXML: Option to deal with existing words in the input file

- calamari_ocr/ocr/text_processing/text_regularizer.py
Fix regex replacements for models where global flags were put at the end of the pattern strings. These patterns are invalid as of Python 3.11. This only applies to models which were created with earlier Calamari 1.x versions that had this kind of regular expression patterns in their defaults.
This PR also reverts @andbue's previous commit which only applied to the default text regularizer parameters - which do not have this issue anymore. @andbue: Hope this is OK for you!
Fixes #348.
> Move global flags to the start of regular expressions

- calamari_ocr/ocr/backends/tensorflow_backend/tensorflow_model.py
In the TensorflowModel constructor, model.summary() is called to output a summary of the model created/loaded. TF's summary() prints itself, but returns None, so the print() around it always prints "None".
OCR-D just configured the amount of noi... console output wanted from TensorFlow, so while I don't get any output from summary() anymore, I do see this spurious "None", which we didn't notice before within the other messages by TF.
Only applies to Calamari 1.0, I think - but I didn't check 2.x very thoroughly.
API docs:
https://www.tensorflow.org/api_docs/python/tf/keras/Model#summary
> calamari/1.0: Remove noisy/useless print around model.summary() call

- calamari_ocr/ocr/predictor.py
This has been overlooked. When using `MultiPredictor.predict_raw` in C1, you had to do a workaround (like `itertools.batched`) to prevent OOM. This just passes on the `batch_size` kwarg to `Predictor.predict_raw`.
> MultiPredictor.predict_raw: pass on batch_size, too

- calamari_ocr/ocr/predict/params.py
This is necessary to allow serialization of `Sample` objects (e.g. when passing results through a `Queue` to another process). Storing the callable (which contains local lambda expressions) in the object would prevent pickling and was not necessary for the calculation of the x positions running once.
> PredictionResult: do not store `out_to_in_trans`

- calamari_ocr/ocr/dataset/data.py
- calamari_ocr/test/test_prediction.py
tfaip provides an option delegating to Tensorflow's [`tf.data.Dataset.bucket_by_sequence_length`](https://www.tensorflow.org/versions/r2.7/api_docs/python/tf/data/Dataset#bucket_by_sequence_length) (also known as _batch width or length bucketing_). This is really helpful for optimal use of memory resources on the GPU: as one tries to increase batch size for GPU utilization one must also be wary of OOM, and this is aggrevated by zero padding – so samples with largest length can spoil an entire batch's memory utilization. So batch bucketing groups batches into similar lengths.
Our CLIs even expose that (e.g. `--pipeline.bucket_boundaries 20 50 100 200 400 800 `), but:
1. the formula for bucket batch sizes was broken prior to tfaip 1.2.7, so one needed to _also_ calculate that (e.g. …
> provide predefined element_length_fn for pipeline.bucket_boundaries
